name: NodeJS with Webpack

on:
    push:
        tags:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
          matrix:
            node-version: [18.x]

        steps:
        - uses: actions/checkout@v3

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: Build
          run: |
            npm install -g pnpm
            pnpm i 
            pnpm run build

        - name: Release
          uses: fnkr/github-action-ghr@v1
          env:
              GHR_COMPRESS: zip
              GHR_PATH: build/
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
